# 서버포트설정
server:
  port: 8080

# database 연동설정
spring:
  application:
    name: moyeo
  datasource:
    #hikari:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/db_moyeo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_moyeo
    password: moyeo!@3456
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/db_moyeo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: user_moyeo
    #password: moyeo!@3456
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.moyeo: debug
    org.mybatis: debug

    # log4jdbc 설정
    jdbc.sqlonly: debug     # SQL 문장 출력
    jdbc.sqltiming: trace   # 실행 시간 출력
    jdbc.resultset: off     # ResultSet 출력 끔
    jdbc.audit: off         # 트랜잭션/커넥션 로그 끔
    jdbc.connection: off    # 커넥션 로그도 끄고 싶으면

# spring data jpa 설정
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform