springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
  packages-to-scan: com.moyeo
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  version: V.0.0.1
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger.html

# 서버포트설정
server:
  port: 8080

# database 연동설정
spring:
  application:
    name: moyeo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_moyeo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_moyeo
    password: moyeo!@3456
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  # spring data jpa 설정
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform